/**
 * Color themes data structures for atoms and molecules
 * 
 * REFERENCES:
 * jmol:            https://jmol.sourceforge.io/jscolors/
 *                  https://sciencenotes.org/molecule-atom-colors-cpk-colors/
 * alt palette:     https://coolors.co/palette/001524-15616d-ffecd1-ff7d00-78290f-f5cb5c
 *                  https://coolors.co/palette/001219-005f73-0a9396-94d2bd-e9d8a6-ee9b00-ca6702-bb3e03-ae2012-9b2226
 */

export enum ColorTheme {
  CPK = 0,
  ALT = 1,
  JMOL = 2,
}

/**
 * first column always null so as to default to cpk_hex property in 
 * `periodic-table-data-complete` package. Will transfer data here
 * if necessary in the future.
 */
type ColorThemeArray = [null, string | null, string | null];

export const colorThemes: Record<string, ColorThemeArray> = {
  H:   [null, "#ffecd1", "#FFFFFF"],
  He:  [null,      null, "#D9FFFF"],
  Li:  [null,      null, "#CC80FF"],
  Be:  [null,      null, "#C2FF00"],
  B:   [null,      null, "#FFB5B5"],
  C:   [null, "#001524", "#909090"],
  N:   [null, "#15616d", "#3050F8"],
  O:   [null, "#FF7D00", "#FF0D0D"],
  F:   [null, "#94d2bd", "#90E050"],
  Ne:  [null,      null, "#B3E3F5"],
  Na:  [null,      null, "#AB5CF2"],
  Mg:  [null,      null, "#8AFF00"],
  Al:  [null,      null, "#BFA6A6"],
  Si:  [null,      null, "#F0C8A0"],
  P:   [null, "#78290f", "#FF8000"],
  S:   [null, "#f5cb5c", "#FFFF30"],
  Cl:  [null, "#94d2bd", "#1FF01F"],
  Ar:  [null,      null, "#80D1E3"],
  K:   [null,      null, "#8F40D4"],
  Ca:  [null,      null, "#3DFF00"],
  Sc:  [null,      null, "#E6E6E6"],
  Ti:  [null,      null, "#BFC2C7"],
  V:   [null,      null, "#A6A6AB"],
  Cr:  [null,      null, "#8A99C7"],
  Mn:  [null,      null, "#9C7AC7"],
  Fe:  [null,      null, "#E06633"],
  Co:  [null,      null, "#F090A0"],
  Ni:  [null,      null, "#50D050"],
  Cu:  [null,      null, "#C88033"],
  Zn:  [null,      null, "#7D80B0"],
  Ga:  [null,      null, "#C28F8F"],
  Ge:  [null,      null, "#668F8F"],
  As:  [null,      null, "#BD80E3"],
  Se:  [null,      null, "#FFA100"],
  Br:  [null, "#94d2bd", "#A62929"],
  Kr:  [null,      null, "#5CB8D1"],
  Rb:  [null,      null, "#702EB0"],
  Sr:  [null,      null, "#00FF00"],
  Y:   [null,      null, "#94FFFF"],
  Zr:  [null,      null, "#94E0E0"],
  Nb:  [null,      null, "#73C2C9"],
  Mo:  [null,      null, "#54B5B5"],
  Tc:  [null,      null, "#3B9E9E"],
  Ru:  [null,      null, "#248F8F"],
  Rh:  [null,      null, "#0A7D8C"],
  Pd:  [null,      null, "#006985"],
  Ag:  [null,      null, "#C0C0C0"],
  Cd:  [null,      null, "#FFD98F"],
  In:  [null,      null, "#A67573"],
  Sn:  [null,      null, "#668080"],
  Sb:  [null,      null, "#9E63B5"],
  Te:  [null,      null, "#D47A00"],
  I:   [null, "#94d2bd", "#940094"],
  Xe:  [null,      null, "#429EB0"],
  Cs:  [null,      null, "#57178F"],
  Ba:  [null,      null, "#00C900"],
  La:  [null,      null, "#70D4FF"],
  Ce:  [null,      null, "#FFFFC7"],
  Pr:  [null,      null, "#D9FFC7"],
  Nd:  [null,      null, "#C7FFC7"],
  Pm:  [null,      null, "#A3FFC7"],
  Sm:  [null,      null, "#8FFFC7"],
  Eu:  [null,      null, "#61FFC7"],
  Gd:  [null,      null, "#45FFC7"],
  Tb:  [null,      null, "#30FFC7"],
  Dy:  [null,      null, "#1FFFC7"],
  Ho:  [null,      null, "#00FF9C"],
  Er:  [null,      null, "#00E675"],
  Tm:  [null,      null, "#00D452"],
  Yb:  [null,      null, "#00BF38"],
  Lu:  [null,      null, "#00AB24"],
  Hf:  [null,      null, "#4DC2FF"],
  Ta:  [null,      null, "#4DA6FF"],
  W:   [null,      null, "#2194D6"],
  Re:  [null,      null, "#267DAB"],
  Os:  [null,      null, "#266696"],
  Ir:  [null,      null, "#175487"],
  Pt:  [null,      null, "#D0D0E0"],
  Au:  [null,      null, "#FFD123"],
  Hg:  [null,      null, "#B8B8D0"],
  Tl:  [null,      null, "#A6544D"],
  Pb:  [null,      null, "#575961"],
  Bi:  [null,      null, "#9E4FB5"],
  Po:  [null,      null, "#AB5C00"],
  At:  [null,      null, "#754F45"],
  Rn:  [null,      null, "#428296"],
  Fr:  [null,      null, "#420066"],
  Ra:  [null,      null, "#007D00"],
  Ac:  [null,      null, "#70ABFA"],
  Th:  [null,      null, "#00BAFF"],
  Pa:  [null,      null, "#00A1FF"],
  U:   [null,      null, "#008FFF"],
  Np:  [null,      null, "#0080FF"],
  Pu:  [null,      null, "#006BFF"],
  Am:  [null,      null, "#545CF2"],
  Cm:  [null,      null, "#785CE3"],
  Bk:  [null,      null, "#8A4FE3"],
  Cf:  [null,      null, "#A136D4"],
  Es:  [null,      null, "#B31FD4"],
  Fm:  [null,      null, "#B31FBA"],
  Md:  [null,      null, "#B30DA6"],
  No:  [null,      null, "#BD0D87"],
  Lr:  [null,      null, "#C70066"],
  Rf:  [null,      null, "#CC0059"],
  Db:  [null,      null, "#D1004F"],
  Sg:  [null,      null, "#D90045"],
  Bh:  [null,      null, "#E00038"],
  Hs:  [null,      null, "#E6002E"],
  Mt:  [null,      null, "#EB0026"],
  Ds:  [null,      null,      null],
  Rg:  [null,      null,      null],
  Cn:  [null,      null,      null],
  Nh:  [null,      null,      null],
  Fl:  [null,      null,      null],
  Mc:  [null,      null,      null],
  Lv:  [null,      null,      null],
  Ts:  [null,      null,      null],
  Og:  [null,      null,      null],
  Uue: [null,      null,      null],
};
